define(
[
	'angular'
	//----
	,'model/sp/service/prompt'
	,'model/sp/api_crud'
    ,'service/db'
]
,function
(
	angular
)
{
	var mod = angular.module('sp/service/duplicate',
	[
		 'sp/service/prompt'
		,'sp/api_crud'
        ,'service/db'		
	]);
	mod.factory('sp/service/duplicate',
	[
		 '$http'
		,'$filter'
		,'$q'
		,'sp/service/prompt'
		,'sp/api_crud'
        ,'service/db/download_product'		
	,function(
		 $http
		,$filter
		,$q
		,prompt_service
		,sp_crud_api
        ,download_product		
	){
		return function(sp){
			var defer = $q.defer();

			prompt_service(null/*original_sp*/,null/*suggest_product*/,sp/*duplicate_sp*/,null/*sku*/,false/*is_operate_offline*/).then(
				function(prompt_result){ 
				 	sp_crud_api.insert_new(prompt_result.sp,prompt_result.sku).then(
				 		function(sp){
				 			download_product(false).then(
				 				function(){
				 					defer.resolve(sp);
				 				},function(reason){
				 					defer.reject(reason);
				 				}
				 			)
				 		},function(reason){
				 			defer.reject(reason);
				 		}
				 	)
				}
				,function(reason){ 
					defer.reject(reason);
				}
			);
			return defer.promise;			
		}
	}]);
})