define(
[
    'angular'
    //----
    ,'app/shortcut_app/service/prompt_child'
]
,function
(
    angular
)
{
    var mod = angular.module('shortcut_app/service/set_child',
    [
        'shortcut_app/service/prompt_child'
    ]);
    mod.factory('shortcut_app/service/set_child',
    [
         '$http'
        ,'$q'
        ,'shortcut_app/service/prompt_child'
    ,function(
         $http
        ,$q
        ,prompt_child_service
    ){
    	return function(parent_pos,child_pos,child){
            var defer = $q.defer();
    		prompt_child_service(child)
    		.then(
    			function(data){
    				$http({
    					url:'/sale_shortcut/set_child_info',
    					method:'POST',
    					data:{
    						parent_position:parent_pos,
    						child_position:child_pos,
    						child_caption:data.caption,
    						product_id:data.store_product.product_id
    					}
    				})
    				.then(
    					function(data){
    						defer.resolve(data.data);
    					},
    					function(reason){
                            defer.reject(reason);
    					}
    				)
    			},
    			function(reason){
    				defer.reject(reason);
    			}
    		)
    		return defer.promise;
    	}
    }])
})